# Generated by Django 2.2 on 2020-11-02 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_meta', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_meta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnswerOption',
            fields=[
                ('metainfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.MetaInfo')),
                ('option_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_correct_ans', models.BooleanField(default=True)),
            ],
            bases=('quiz.metainfo',),
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('metainfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.MetaInfo')),
                ('question', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('answer_options', models.ManyToManyField(blank=True, to='quiz.AnswerOption')),
            ],
            bases=('quiz.metainfo',),
        ),
        migrations.CreateModel(
            name='QuizSubmission',
            fields=[
                ('metainfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.MetaInfo')),
                ('is_active', models.BooleanField(default=True)),
                ('answer', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_option', to='quiz.AnswerOption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Questions')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('quiz.metainfo',),
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('metainfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='quiz.MetaInfo')),
                ('is_active', models.BooleanField(default=True)),
                ('submission', models.ManyToManyField(blank=True, related_name='user_submissions', to='quiz.QuizSubmission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_user', to=settings.AUTH_USER_MODEL)),
            ],
            bases=('quiz.metainfo',),
        ),
    ]
