# Generated by Django 2.2 on 2020-11-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20201102_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='no_of_questions',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
